CREATE TABLE [dbo].[Client]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[UserId] NVARCHAR(128) NOT NULL DEFAULT '%REPLACE_ME%',
	[FirstName] NVARCHAR(50) NOT NULL, 
	[LastName] NVARCHAR(50) NOT NULL, 
	[Enabled] BIT NOT NULL DEFAULT 1,
	[IsDefault] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [FK_Client_ToUser] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
)
