CREATE TABLE [dbo].[Provider]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[UserId] NVARCHAR(128) NOT NULL DEFAULT '%REPLACE_ME%',
	[Name] VARCHAR(20) NOT NULL, 
	[Enabled] BIT NOT NULL DEFAULT 1,
	[IsDefault] BIT NOT NULL DEFAULT 0, 
	CONSTRAINT [FK_Provider_ToUser] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
)
