CREATE TABLE [dbo].[Rate]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[UserId] NVARCHAR(128) NOT NULL ,
	[StartDate] DATETIME2 NOT NULL, 
	[EndDate] DATETIME2 NULL, 
	[Rate] FLOAT NOT NULL,
	CONSTRAINT [FK_Rate_ToUser] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
)
